version: "3"
services:
  jenkins:
    container_name: jenkins-angular
    image: jenkins/jenkins:alpine
    ports:
      - "8080:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
    networks:
      - net_jenkins
  
  sonarqube:
    image: "sonarqube"
    ports:
      - "9000:9000"
    networks:
      - net_jenkins
volumes:
  jenkins_home:
networks:
  net_jenkins:
